SET VERIFY OFF
connect "SYS"/"&&sysPassword" as SYSDBA
set echo on
spool d:\oracle\admin\orcl\scripts\CreateDBFiles.log append
CREATE SMALLFILE TABLESPACE "USERS" LOGGING DATAFILE 'd:\oracle\oradata\orcl\users01.dbf' SIZE 5M REUSE AUTOEXTEND ON NEXT  1280K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO;
ALTER DATABASE DEFAULT TABLESPACE "USERS";
spool off
